
# Generated by Django 3.2 on 2023-05-04 14:10

import django.contrib.auth.validators
from django.db import migrations, models

# Generated by Django 3.2 on 2023-05-03 07:20

from django.db import migrations, models
import users.validators



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',

            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),

            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Имя пользователя'),

        ),
    ]
